version: '3.8'

services:
  nginx:
    image: local-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Correct file mapping
    networks:
      - nginx-network

  python-app:
    image: local-python-app
    ports:
      - "8000" 
    deploy:
      replicas: 3  # Scale to 3 instances (for example)
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
